# Generated by Django 5.1.3 on 2024-12-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicador', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('frequencia', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_posto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacao', models.CharField(max_length=255)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='pagina.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='pagina.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pagina.indicador')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pagina.metas')),
            ],
        ),
        migrations.CreateModel(
            name='SetorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='pagina.grupoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('tipo_produto', models.CharField(max_length=100)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pagina.setorproduto')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorPosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='pagina.indicador')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='pagina.posto')),
            ],
            options={
                'unique_together': {('indicador', 'posto')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pagina.indicador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='pagina.produto')),
            ],
            options={
                'unique_together': {('produto', 'indicador')},
            },
        ),
    ]
