# Generated by Django 5.1.3 on 2024-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_grupoproduto_indicador_posto_conjuntoindicadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoproduto',
            name='nome',
            field=models.CharField(default='Default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
