# Generated by Django 5.1.3 on 2024-12-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_grupoproduto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='frequencia',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='metas',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.indicador'),
        ),
    ]
